### PR TITLE
Fix CI tests

### PR DESCRIPTION
**Pull request by rossviljoen**
Copies CI test setup from ApproximateGPs

### CODE REVIEW

**Comment by willtebbutt** [comment]
Looks like the Window's runner doesn't have enough memory. I wonder whether the ubuntu failures are also caused by out-of-memory problems?

**Comment by rossviljoen** [comment]
The last commit is showing up on the branch but not on this pr somehow?

**Comment by willtebbutt** [comment]
> The last commit is showing up on the branch but not on this pr somehow?

Maybe you need to rebase onto master? My git knowledge is bad. Either way, I wouldn't worry about it.

**Review by willtebbutt — APPROVED** [review]
Okay. I'm happy for this to go in when CI passes (looks like it's going to). I would imagine that the tests on the empirical covariance are probably still good enough to prevent any really bad bugs from creeping in, so probably 1_000 samples is fine.

**Pull request merged**
